apiVersion: v1
kind: Pod
metadata:
  name: cni-fixer-node-02
  namespace: default
spec:
  nodeName: talos-core-02
  hostNetwork: true
  containers:
  - name: fixer
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      rm /host/etc/cni/net.d/05-cilium.conflist
      mv /host/etc/cni/net.d/10-flannel.conflist.cilium_bak /host/etc/cni/net.d/10-flannel.conflist
      echo "Fixed node 02"
      sleep 60
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-etc
      mountPath: /host/etc
  volumes:
  - name: host-etc
    hostPath:
      path: /etc
---
apiVersion: v1
kind: Pod
metadata:
  name: cni-fixer-node-03
  namespace: default
spec:
  nodeName: talos-core-03
  hostNetwork: true
  containers:
  - name: fixer
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
    - |
      rm /host/etc/cni/net.d/05-cilium.conflist
      mv /host/etc/cni/net.d/10-flannel.conflist.cilium_bak /host/etc/cni/net.d/10-flannel.conflist
      echo "Fixed node 03"
      sleep 60
    securityContext:
      privileged: true
    volumeMounts:
    - name: host-etc
      mountPath: /host/etc
  volumes:
  - name: host-etc
    hostPath:
      path: /etc
