apiVersion: v1
kind: Pod
metadata:
  name: debug-check
spec:
  nodeName: talos-core-01
  hostPID: true
  restartPolicy: Never
  containers:
  - name: check
    image: alpine
    volumeMounts:
    - name: host-root
      mountPath: /host
    command: 
      - "/bin/sh"
      - "-c"
      - |
        MNT_PATH=$(find /host/run/containerd/io.containerd.runtime.v2.task/system/kubelet/rootfs -name mount -type f | head -n 1)
        echo "Kubelet mount path: $MNT_PATH"
        ldd $MNT_PATH || echo "ldd failed"
        
        echo "Creating /host/var/lib/longhorn/bin..."
        mkdir -p /host/var/lib/longhorn/bin
        
        echo "Copying mount..."
        cp $MNT_PATH /host/var/lib/longhorn/bin/mount
        chmod +x /host/var/lib/longhorn/bin/mount
        
        echo "Testing mount execution from host via nsenter..."
        nsenter -t 1 -m -u -n -i -- /var/lib/longhorn/bin/mount --version
  volumes:
  - name: host-root
    hostPath:
      path: /
