apiVersion: v1
kind: Pod
metadata:
  name: debug-check
spec:
  nodeName: talos-core-01
  hostPID: true
  restartPolicy: Never
  containers:
  - name: check
    image: alpine
    command: 
      - "/bin/sh"
      - "-c"
      - |
        echo "Checking for mount in common locations..."
        nsenter -t 1 -m -u -n -i -- /usr/bin/mount --version || echo "/usr/bin/mount failed"
        nsenter -t 1 -m -u -n -i -- /bin/mount --version || echo "/bin/mount failed"
        nsenter -t 1 -m -u -n -i -- /usr/local/bin/mount --version || echo "/usr/local/bin/mount failed"
        nsenter -t 1 -m -u -n -i -- /sbin/mount --version || echo "/sbin/mount failed"
    securityContext:
      privileged: true
