---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# Prometheus Stack for monitoring
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  version: 55.5.0
  targetNamespace: monitoring
  valuesContent: |-
    prometheus:
      prometheusSpec:
        nodeSelector:
          topology.kubernetes.io/zone: core
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Gi
        retention: 30d
        retentionSize: "45GB"

    grafana:
      nodeSelector:
        topology.kubernetes.io/zone: core
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 10Gi
      adminPassword: changeme  # Change in production!

    alertmanager:
      alertmanagerSpec:
        nodeSelector:
          topology.kubernetes.io/zone: core
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi

    # Scrape edge nodes when they're online
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
# Loki for log aggregation
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: loki
  namespace: logging
spec:
  repo: https://grafana.github.io/helm-charts
  chart: loki-stack
  version: 2.9.11
  targetNamespace: logging
  valuesContent: |-
    loki:
      nodeSelector:
        topology.kubernetes.io/zone: core
      persistence:
        enabled: true
        storageClassName: longhorn
        size: 50Gi
      config:
        limits_config:
          retention_period: 168h  # 7 days

    promtail:
      # Deploy on all nodes to collect logs
      tolerations:
      - operator: Exists
---
# Uptime monitoring for edge nodes
apiVersion: v1
kind: ConfigMap
metadata:
  name: uptime-monitor-config
  namespace: monitoring
data:
  targets.yaml: |
    # Edge node uptime monitoring
    targets:
      - name: talos-edge-01
        ip: 10.0.1.21
        mac: 00:00:00:00:01:01
      - name: talos-edge-02
        ip: 10.0.1.22
        mac: 00:00:00:00:01:02
      - name: talos-edge-03
        ip: 10.0.1.23
        mac: 00:00:00:00:01:03
