---
# Homelab Talos Cluster Node Inventory
# All nodes are defined here with their roles, IPs, and configuration

cluster:
  name: homelab
  endpoint: https://10.0.0.10:6443  # VIP for control plane
  domain: cluster.local

# Core nodes - always-on, host control plane and critical workloads
core_nodes:
  - hostname: talos-core-01
    ip: 10.0.0.11
    role: controlplane
    mac: 00:00:00:00:00:01
    specs:
      cpu: 4
      memory: 8192  # MB
      disk: /dev/sda
    labels:
      node-role.kubernetes.io/control-plane: ""
      topology.kubernetes.io/zone: core
      
  - hostname: talos-core-02
    ip: 10.0.0.12
    role: controlplane
    mac: 00:00:00:00:00:02
    specs:
      cpu: 4
      memory: 8192
      disk: /dev/sda
    labels:
      node-role.kubernetes.io/control-plane: ""
      topology.kubernetes.io/zone: core
      
  - hostname: talos-core-03
    ip: 10.0.0.13
    role: controlplane
    mac: 00:00:00:00:00:03
    specs:
      cpu: 4
      memory: 8192
      disk: /dev/sda
    labels:
      node-role.kubernetes.io/control-plane: ""
      topology.kubernetes.io/zone: core
      
  - hostname: talos-core-04
    ip: 10.0.0.14
    role: worker
    mac: 00:00:00:00:00:04
    specs:
      cpu: 8
      memory: 16384
      disk: /dev/sda
    labels:
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: core
      storage-node: "true"  # Longhorn storage
      
  - hostname: talos-core-05
    ip: 10.0.0.15
    role: worker
    mac: 00:00:00:00:00:05
    specs:
      cpu: 8
      memory: 16384
      disk: /dev/sda
    labels:
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: core
      storage-node: "true"  # Longhorn storage

# Edge nodes - on-demand via WoL, tainted to prevent regular scheduling
edge_nodes:
  - hostname: talos-edge-01
    ip: 10.0.1.21
    role: worker
    mac: 00:00:00:00:01:01
    specs:
      cpu: 4
      memory: 8192
      disk: /dev/sda
    labels:
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: edge
    taints:
      - key: node-role.kubernetes.io/edge
        value: "true"
        effect: NoSchedule
      
  - hostname: talos-edge-02
    ip: 10.0.1.22
    role: worker
    mac: 00:00:00:00:01:02
    specs:
      cpu: 4
      memory: 8192
      disk: /dev/sda
    labels:
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: edge
    taints:
      - key: node-role.kubernetes.io/edge
        value: "true"
        effect: NoSchedule
      
  - hostname: talos-edge-03
    ip: 10.0.1.23
    role: worker
    mac: 00:00:00:00:01:03
    specs:
      cpu: 4
      memory: 8192
      disk: /dev/sda
    labels:
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: edge
    taints:
      - key: node-role.kubernetes.io/edge
        value: "true"
        effect: NoSchedule

# Network configuration
network:
  opnsense_ip: 10.0.0.1
  subnet: 10.0.0.0/16
  gateway: 10.0.0.1
  nameservers:
    - 10.0.0.1  # OPNsense with split DNS
  wol_gateway: 10.0.0.1  # WoL requests sent via OPNsense
