---
# Homelab Talos Cluster Node Inventory
# All nodes are defined here with their roles, IPs, and configuration

cluster:
  name: homelab
  endpoint: https://10.10.0.10:6443  # VIP for control plane
  domain: cluster.local

# Core nodes - always-on, host control plane and critical workloads
# Hardware: 3x Fujitsu Esprimo (64GB RAM, i5-7400T)
# Networking: eth0 (2.5G USB Realtek)
core_nodes:
  - hostname: talos-core-01
    ip: 10.10.0.11
    role: controlplane
    mac: 00:e0:4c:68:13:1f # 2.5G USB Realtek
    specs:
      cpu: 4
      memory: 65536
      disk: /dev/sda
      data_disks:
        - /dev/sdb
    labels:
      node-role.kubernetes.io/control-plane: ""
      topology.kubernetes.io/zone: core
      node-role: core
      availability: always-on
      storage: longhorn

  - hostname: talos-core-02
    ip: 10.10.0.12
    role: controlplane
    mac: 00:e0:4c:68:13:4b # 2.5G USB Realtek
    specs:
      cpu: 4
      memory: 65536
      disk: /dev/nvme0n1
      data_disks:
        - /dev/sda
        - /dev/sdb
    labels:
      node-role.kubernetes.io/control-plane: ""
      topology.kubernetes.io/zone: core
      node-role: core
      availability: always-on
      storage: longhorn

  - hostname: talos-core-03
    ip: 10.10.0.13
    role: controlplane
    mac: 00:e0:4c:68:0a:78 # 2.5G USB Realtek
    specs:
      cpu: 4
      memory: 65536
      disk: /dev/nvme0n1
      data_disks:
        - /dev/sda
        - /dev/sdb
    labels:
      node-role.kubernetes.io/control-plane: ""
      topology.kubernetes.io/zone: core
      node-role: core
      availability: always-on
      storage: longhorn

# Edge nodes - on-demand via WoL, tainted to prevent regular scheduling
# Hardware: 2x Minisforum N100 (8GB RAM)
# Networking: eth0 (2.5G), eth1 (2.5G)
edge_nodes:
  - hostname: talos-edge-01
    ip: 10.10.0.21
    role: worker
    mac: 00:00:00:00:01:01
    specs:
      cpu: 4
      memory: 8192
      disk: /dev/nvme0n1
    labels:
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: edge
      node-role: edge
      availability: intermittent
    taints:
      - key: edge
        value: "true"
        effect: NoSchedule

  - hostname: talos-edge-02
    ip: 10.10.0.22
    storage_ip: 10.10.1.22
    role: worker
    mac: 00:00:00:00:01:02
    specs:
      cpu: 4
      memory: 8192
      disk: /dev/nvme0n1
    labels:
      node-role.kubernetes.io/worker: ""
      topology.kubernetes.io/zone: edge
      node-role: edge
      availability: intermittent
    taints:
      - key: edge
        value: "true"
        effect: NoSchedule

# Network configuration
network:
  opnsense_ip: 10.10.0.1
  subnet: 10.10.0.0/24
  gateway: 10.10.0.1
  nameservers:
    - 10.10.0.1  # OPNsense with split DNS
  wol_gateway: 10.10.0.1  # WoL requests sent via OPNsense
  broadcast: 10.10.0.255
