---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
---
# Cilium CNI - recommended for Talos
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cilium
  namespace: kube-system
spec:
  repo: https://helm.cilium.io/
  chart: cilium
  version: 1.14.5
  targetNamespace: kube-system
  valuesContent: |-
    ipam:
      mode: kubernetes
    kubeProxyReplacement: strict
    k8sServiceHost: 10.10.0.10  # Cluster VIP
    k8sServicePort: 6443
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
# NGINX Ingress Controller
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  repo: https://kubernetes.github.io/ingress-nginx
  chart: ingress-nginx
  version: 4.8.3
  targetNamespace: ingress-nginx
  valuesContent: |-
    controller:
      kind: DaemonSet
      service:
        type: LoadBalancer
        externalIPs:
          - 10.10.0.50  # LoadBalancer IP
      nodeSelector:
        topology.kubernetes.io/zone: core
      tolerations: []
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
# cert-manager for TLS certificates
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: v1.13.3
  targetNamespace: cert-manager
  valuesContent: |-
    installCRDs: true
    nodeSelector:
      topology.kubernetes.io/zone: core
---
# Multus CNI for secondary storage network
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: multus
  namespace: kube-system
spec:
  repo: https://k8snetworkplumbingwg.github.io/helm-charts
  chart: multus
  version: 4.0.2
  targetNamespace: kube-system
  valuesContent: |-
    config:
      enabled: true
